#!/bin/sh

if [ -a /home/nir/scripts/current_stereo ]
then
        rm /home/nir/scripts/current_stereo && sh /home/nir/scripts/surround
else
        touch /home/nir/scripts/current_stereo && sh /home/nir/scripts/stereo
fi

