#! /bin/sh
#
# Panel config for LemonBoy's bar
# Reads lines from /tmp/panel-fifo

while read -r line ; do
    case $line in
        S*)
            # clock output
            clock="${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    O*) wm_infos="$wm_infos\\u1 \\f6\\fr \\ur" ;; # focused occupied desktop
                    F*) wm_infos="$wm_infos\\u1 \\f6\\fr \\ur" ;; # focused free desktop
                    U*) wm_infos="$wm_infos\\u1\\b4 \\f8\\fr \\br\\ur" ;; # focused urgent desktop
                    o*) wm_infos="$wm_infos \\f6\\fr " ;; # occupied desktop
                    f*) wm_infos="$wm_infos \\f8\\fr " ;; # free inactive desktop
                    u*) wm_infos="$wm_infos\\b4 \\f8\\fr \\br" ;; # urgent desktop
                esac
                shift
            done
            ;;
    esac


    # bring it all together
    middle="$clock  "
    #right="$wifi "
    # and print to bar
    #printf "%s\n" "$left\\c$middle\\r$right"
    printf "%s\n" "$wm_infos\\c$middle"

done
