#!/bin/sh

# developing environment
tmux has-session -t code
if [ $? != 0 ]
then
        tmux new-session -s code -n vim -d
        tmux send-keys -t code 'cd ~/work/code' C-m
        tmux send-keys -t code 'vim .' C-m
        tmux split-window -h -t code
        tmux send-keys -t code:1.2 'cd ~/work/code && clear' C-m
        tmux split-window -v -t code
        tmux send-keys -t code:1.3 'cd ~/work/code && clear' C-m
        tmux new-window -n logs -t code
        tmux send-keys -t code:2 'cd ~/work/code && clear' C-m
        tmux select-window -t code:1
        tmux select-pane -t code:1.1
fi

# chat
tmux has-session -t chat
if [ $? != 0 ]
then
        tmux new-session -s chat -n weechat -d 2>&1
        tmux send-keys -t chat 'weechat-curses' C-m
else
        tmux attach -t chat
fi

# music
tmux has-session -t music
if [ $? != 0 ]
then
        tmux new-session -s music -n cmus -d 2>&1
        tmux send-keys -t music 'cd ~/music && cmus' C-m
        tmux send-keys -t music '5' C-m # goto cmus browser view
fi

# files
tmux has-session -t file
if [ $? != 0 ]
then
        tmux new-session -s file -n ranger -d 2>&1
        tmux send-keys -t file 'cd && ranger' C-m
fi
