#!/usr/bin/env perl
use App::Cope;

my @headers = qw[Device Boot Start End Blocks Id System];

sub process {
  if (/^\s*Device/) {
    for my $h (@headers) { mark $h => 'underline'; }
  }
  else {
    line qr{(?:^|:)(\S+/)(\S+)(?:\s+(\*))?} => 'blue', 'blue bold', 'red bold';

    line qr{^(Disk )(\S+?)(: )(\S+ GB)} =>
      map { ( "underline", "underline $_" ) } 'red bold', 'red bold';
  }
}

run( \&process, real_path, @ARGV );
