#!/usr/bin/env perl
use App::Cope;

sub process {
  line qr{^((?:....:)?..:..\..)\s([^:]+:|"[^"]+")} => 'red', 'blue bold';
  mark qr{\(rev \d+\)} => 'black bold';
}

run( \&process, real_path, @ARGV );
